name: IronManSyliusProductOnDemandPlugin
version: 1.0.3
description: A Sylius plugin that adds new features to the Sylius e-commerce platform.
author: John Doe
author_email: a.rhul@creatiswbart.com
license: MIT
resources:
    templates:
        resources:
            - "@IronManSyliusProductOnDemandPlugin/templates"
